# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0166ee9fbce885c510a70214c6a8d08ab84b8d491f409ce6496c3f9bf8825bf7668186d9f598259bdee3892c1c69f3cb1de2ac7c1c826e2de38a9223b7bc8ce

test:
  secret_key_base: 696ac6f06bf47b322bcb6f66c9248beecbdc74c9fae5e29a641f06f3e3c1881facafe644451e735e215bed946b9c887ce94fdebb453ee7c1a8d4a7c51adb643d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
